# Generated by Django 4.2.4 on 2023-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(max_length=100, null=True, verbose_name='fabricator'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
